# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - dil:/data/db
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}

  mongo-save:
    image: python3.7
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.docker
    build: .

volumes:
  dil:
